### ISSUE TITLE
PERCON source code request

### ISSUE THREAD

**Issue by YoannPa** [alrsat/PERCON#1]
Hi, 
Would it be possible to share the source code of PERCON in the repository ?
I would like to see if I could adapt it so that it can work on Linux.
Thank you in advance for your help.

**Comment by enigene** [comment]
Hi, Yoann! Unfortunately, the developer of PERCON, Valery Shepelev, did not provide us with the source code. Try writing him a personal letter (by email spl@img.msk.ru) and asking him about it.

**Comment by YoannPa** [comment]
Okay ! Thank you for your answer.
